### ISSUE TITLE
Can it run in windows systems?

### ISSUE THREAD

**Issue by ZJU-XWK** [alexxu1988/ADJSCC#1]

**Comment by ZJU-XWK** [comment]
windows系统可以运行吗？我运行后有问题，主要是tensorflow-compression库的问题

**Comment by alexxu1988** [comment]
代码提供的tensorflow-compression包是基于Linux编译的，不能在windows上运行。如果你想运行在windows,你获取可以尝试安装tensorflow-compression=2.0b2 (https://github.com/tensorflow/compression) 进行替代。由于时间关系，我没有测试过这个版本。

**Comment by ZJU-XWK** [comment]
请问您有复现过这篇文章吗？“Deep Joint Source-Channel Coding for Wireless Image Transmission”，这篇文章也是您的paper里的参考文献之一。

**Comment by ZJU-XWK** [comment]
最近刚接触深度学习和tensorflow。还有一个问题，如果不安装tensorflow-compression2.0b2,我可以用Keras的相关API代替代码里的tfc吗？

**Comment by alexxu1988** [comment]
复现过，psnr性能比论文原文差1dB左右，可能和训练技巧有关。Keras中没有对应tfc GDN的API。

**Comment by ZJU-XWK** [comment]
那你能提供那篇文章的代码吗？

**Comment by ZJU-XWK** [comment]
我也在复现，失败了

**Comment by ZJU-XWK** [comment]
有个小请求，我能加你的VX吗？

**Comment by ZJU-XWK** [comment]
主要是想看看你的代码是怎么复现那篇文章的，我现在一直没能成功

**Comment by alexxu1988** [comment]
就和这篇文章一样，把激活函数改成prelu，没有特殊之处，你复现不出来和你选取的tensorflow，keras版本有关。

发自我的iPhone

**Comment by ZJU-XWK** [comment]
好的，谢谢

**Comment by ZJU-XWK** [comment]
感谢你的指导，我现在已经能复现“Deep Joint Source-Channel Coding for Wireless Image Transmission”了。这篇paper把Deep JSCC的方案与传统的SSCC（JPEG+LDPC+QAM）做对比。我想问问JPEG和LDPC编码有相关的函数库可以实现吗？

**Comment by alexxu1988** [comment]
Matlab有库可以实现

发自我的iPhone

**Comment by ZJU-XWK** [comment]
十分感谢

**Comment by ZJU-XWK** [comment]
MATLAB是不是没有JPEG编解码的库函数？

**Comment by ZJU-XWK** [comment]
Sorry, I haven't try it in windows systems




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "alexxu1988"<notifications@github.com&gt;; 
发送时间: 2021年3月5日(星期五) 中午11:44
收件人: "alexxu1988/ADJSCC"<ADJSCC@noreply.github.com&gt;; 
抄送: "今生有约"<2568453700@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [alexxu1988/ADJSCC] Can it run in windows systems? (#1)





 
Closed #1.
