### ISSUE TITLE
quantification

### ISSUE THREAD

**Issue by sun107** [alexxu1988/ADJSCC#2]
您好！我最近正在阅读您的论文，感觉受益良多。有个小问题想请教您，在您训练和测试的过程中，有特征图量化这个过程吗？谢谢！

**Comment by alexxu1988** [comment]
论文的训练过程和测试过程均没有，如果想看量化误差，在测试时可以使用round函数进行量化。我进行过实验，不会有太大的量化误差。

发自我的iPhone

**Comment by sun107** [comment]
> 论文的训练过程和测试过程均没有，如果想看量化误差，在测试时可以使用round函数进行量化。我进行过实验，不会有太大的量化误差。 发自我的iPhone
> […](#)
> 在 2021年7月22日，下午3:26，sun107 ***@***.***> 写道： ﻿ 您好！我最近正在阅读您的论文，感觉受益良多。有个小问题想请教您，在您训练和测试的过程中，有特征图量化这个过程吗？谢谢！ — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

十分感谢您的回复！
